#!/usr/bin/env python3
"""Build the browser bundle used by both file:// and static HTTP hosting."""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path


REPOSITORY = Path(__file__).resolve().parents[1]
SITE = REPOSITORY / "static-mockup"
ASSETS = SITE / "assets"
OUTPUT = ASSETS / "app.static.js"


def read_source(name: str) -> str:
    return (ASSETS / name).read_text(encoding="utf-8").strip()


def remove_imports(source: str) -> str:
    return re.sub(r"^import\s+.*?;\s*$", "", source, flags=re.MULTILINE).lstrip()


def remove_exports(source: str) -> str:
    return re.sub(r"\bexport\s+(?=(?:const|function)\b)", "", source)


def load_data() -> dict[str, object]:
    return {
        data_file.stem: json.loads(data_file.read_text(encoding="utf-8"))
        for data_file in sorted((SITE / "data").glob("*.json"))
    }


def build_bundle() -> str:
    layout = remove_exports(read_source("layout.js"))
    pages = remove_exports(remove_imports(read_source("pages.js")))
    app = remove_imports(read_source("app.js"))
    data = json.dumps(load_data(), ensure_ascii=False, separators=(",", ":"))
    return (
        "/* Generated by scripts/build_static_bundle.py. Do not edit directly. */\n"
        ";(async function(){\n"
        f"globalThis.QA_STATIC_DATA={data};\n\n"
        f"{layout}\n\n{pages}\n\n{app}\n"
        "})();\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail when the committed bundle does not match its source files",
    )
    args = parser.parse_args()
    expected = build_bundle()

    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != expected:
            print(
                "Static bundle is out of date. Run scripts/build_static_bundle.py.",
                file=sys.stderr,
            )
            return 1
        print("Static offline bundle is current")
        return 0

    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Built {OUTPUT.relative_to(REPOSITORY)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
